const API_END_POINTS = {
    AUTH: {
        LOGIN: `v3/auth/login`,
        SIGNUP: `v3/auth/signup`,
        RESET_PASSWORD: `v3/auth/resetPassword`,
        FORGET_PASSWORD: `v3/auth/forgetPassword`,
        GET_AUTH_TOKEN: `v3/auth/getAuthToken`,
    },
    APP_BUILDER: {
        JSON: 'v3/organization/appBuilderJSON',
    },
    ORGANIZATION: {
        ADD_ORGANIZATION: `v3/organization/addOrganization`,
        ORG_SETTINGS: `v3/common/orgWorkSettings`,
        GET_WORK_PREFERENCE: `v3/common/getWorkSettings `,
    },
    MANAGER: {
        ACTIVATE_MANAGER_EMAIL: `v3/manager/activateManagerEmail`,
        GET_MANAGER_PROFILE: 'v3/manager/getProfile',
        UPDATE_MANAGER_PROFILE: 'v3/manager/updateProfile',
        VALIDATE_MANAGER_PASSWORD: 'v3/manager/verifyPassword',
        UPDATE_MANAGER_PASSWORD: 'v3/manager/updatePassword',
        GET_PLAN_DETAILS: `v3/manager/getMyScope`,
        RELEASE_NOTES: `v3/releaseNotes/getReleaseNotes`,
    },
    PROCESS: {
        PROCESS_LIST: `v3/process/processList`,
        MAIN: `v3/process`,
        ACTIVATE: 'v3/process/activate',
        DE_ACTIVATE: 'v3/process/activate',
        VALIDATE: 'v3/process/processValidation',
        SHEET_ACTIVATE: 'v3/process/sheetActivate',
        CLONE_TEMPLATE: 'v3/process/cloneTemplate',
        REMOVE_TEMPLATES: '/v3/process/deleteTemplate',
        LIST_TEMPLATES: 'v3/process/templates',
        UPDATE_PROCESS_ORDERED_AT: 'v3/process/updateOrderedAt',
        RESET_PROCESS_ORDERED_AT: 'v3/process/resetOrderedAt',
        IDENTIFIER: 'v3/process/identifier',
        VALIDATE_SHEET_QUERY: 'v3/process/validateSheetQuery',
        VALIDATE_SHEET_QUERY_V2: 'v3/process/validateSheetQueryV2',
        CLONE_PROCESS: 'v3/process/cloneProcess',
        CONFLICT_FINDER: 'v3/process/processConfictFinder',
        DELETE_VALIDATION: `/v4/process/deleteValidation`,
        CURRENT_ACTIVATION: `v3/process/currentActivation`,
        ACTIVATE_ESTIMATION: `v3/process/activateestimate`,
        ABORT_ACTIVATION: `v3/process/abortActivation`,
    },
    TASK: {
        MAIN: `v3/tasks`,
        CLONE: `v3/cloneTask`,
        GET_TASK: `v3/tasks/getTasks`,
    },
    FORM: {
        MAIN: `v3/forms`,
        CLONE: `v3/cloneForm`,
    },
    ENTRIES: {
        ENTRIES_LIST: `v3/entries`,
        IDENTIFIER_TIMELINE: `v3/entries/getIdentifierTimeline`,
        IDENTIFIERS_LIST: `v3/entries/identifierList`,
    },
    COMMON: {
        INIT: `v3/common/init`,
    },
    QUESTIONS: {
        MAIN: `v3/questions`,
    },
    TEAMS: {
        MAIN: `v3/team`,
        ADD_TEAM: `v3/team/addTeam`,
        UPDATE_TEAM: `v3/team/updateTeam`,
        DELETE_TEAM: `v3/team/deleteTeam`,
        GET_TEAM: 'v3/team/getTeam',
        ADD_USERS_TO_TEAM: `v3/team/addUsersToTeam`,
        REMOVE_USERS_FROM_TEAM: `v3/team/removeUsersToTeam`,
        BULK_DELETE_TEAMS: 'v3/team/deleteManyTeams',
    },
    USERS: {
        GET_USER: 'v3/user/getUser',
        ADD_USER: 'v3/user/addUser',
        DELETE_USER: 'v3/user/deleteUser',
        UPDATE_USER: 'v3/user/updateUser',
        DEACTIVATE_USER: 'v3/user/deactivateUser',
        ACTIVATE_USER: 'v3/user/activateUser',
        BULK_USER_UPLOAD: 'v3/user/bulkUploadUser',
        BULK_DELETE_USERS: 'v3/user/deleteManyUsers',
    },
    SHEETS: {
        MAIN: `v3/sheets`,
        VALIDATE_SHEET_ID: `v3/sheets/validate`,
        GET_SHEETS: `v3/sheets/list`,
        GET_SHEETS_DATA: `v4/sheets/getSheetData`,
        DELETE_SHEET_ROW: `v3/sheets/deleteSheetRow`,
        EXPORT_SHEETS_DATA: 'v4/sheets/getSheetData',
        DELETE_SHEET_ROWS: `v4/sheets/bulkDeleteSheetData`,
        ADD_ROW: 'v3/sheets/addSheetRow',
        BATCH_UPDATE: `v3/sheets/batchUpdate`,
        SINGLE_ROW_EDIT: `v3/sheets/updateSheetRow`,
        BATCH_BULK_UPDATE: `v4/sheets/bulkEditSheetData`,
        COLUMNS: `v3/columns`,
        BULK_DELETE_SHEETS: `v3/sheets/bulkDelete`,
    },
    PDF: {
        MAIN: 'v4/excel/parseExcel',
    },
    DATASET: {
        GET_DATASET: 'v3/dataset/getDatasetList',
        DELETE_DATASET: 'v3/dataset/deleteDataset',
        UPDATE_DATASET: 'v3/dataset/updateDatasetDetails',
        ADD_DATASET: 'v3/dataset/addDataset',
        GET_DATASET_DATA: 'v3/dataset/getDatasetData',
        DEL_DATASET_DATA: 'v3/dataset/deleteDatasetRow',
        ADD_COLUMN: 'v3/dataset/addColumnToDataset',
        ADD_ROW: 'v3/dataset/addRowtoDatasetJson',
    },
    PAGE_BUILDER: {
        PAGE: 'v3/page',
        RUN_QUERY: 'v3/page/getQuery',
        PAGE_DRAFT_STATE: 'v3/page/draftState',
        PAGE_MAIN_STATE: 'v3/page/live',
        WIDGET_MAIN_STATE: 'v3/widgets/live',
        GET_PAGE_LIST: 'v3/page/getPageList',
        GET_PAGE_DATA: 'v3/page/getPageData',
        WIDGET: 'v3/widgets',
        GET_WIDGET: 'v3/widgets/getWidget',
        GET_WIDGET_DATA: 'v3/widgets',
    },
    INPUT_FORM: {
        GET_USERS_AND_TEAM: 'v3/questions/agent/getUserAndTeamData',
        GET_DROPDOWN: 'v3/questions/agent/getDropdownData',
        SUBMIT_RESPONSE: '/v3/process/agent/response',
        RUN_QUERY: '/v3/process/agent/sheetQuery',
        GET_DEPENDENT_DROPDOWN_DATA: '/v3/sheets/getDependentDropdown',
    },
    GEOCODE: {
        GEO_CODE_REVERSE: 'v3/common/location/getAddress',
        GEO_CODE: 'v3/common/location/searchAddress',
    },
    UPLOAD: {
        UPLOAD_EXCEL_FILE: 'v3/upload/excelUpload',
        FILE: 'v3/upload/file',
    },
    EXCEL_LOGS: {
        GET_EXCEL_LOGS: 'v3/excelLog',
    },
    REDASH: {
        GET_TOKEN: 'v3/redash/generateLoginKey',
        DASHBOARD_LIST: 'v3/redash/getDashboardList',
        GENERATE_PUBLIC_URL: 'v3/redash/generatePublicUrl',
    },
    METABASE: {
        GET_TOKEN: 'v3/metabase/metabaseToken',
        DASHBOARD_LIST: 'v3/metabase/getDashboardList',
        AGENT_DASHBOARD: 'v3/metabase/getDashboardAgent',
        GENERATE_PUBLIC_URL: 'v3/metabase/generatePublicUrl',
        EXTERNAL_DASHBOARD_LIST: 'v4/userwisemetabase',
    },
    ACCOUNT_USER: {
        GET_ACCOUNT_USER: 'v3/admin/accoutUsers',
        ADD_USER: '/v3/admin/addAccountUser',
        DELETE_USER: '/v3/admin/deleteAccountUser',
        EDIT_USER: 'v3/admin/editAccountUser',
        DEACTIVATE_USER: 'v3/admin/deactivateUserAccountUser',
        RESEND_INVITE_USER: 'v3/admin/resendInviteAccountUser',
        VERIFY_ACCOUNT_USER: 'v3/admin/verifyAccountUser',
        VERIFY_SIGN_UP: 'v3/accountUser/auth/signup',
    },
    TEMPLATES: {
        GET_TEMPLATES: 'v3/template/getTemplates',
        GET_TEMPLATES_CATEGORIES: '/v3/template/categories',
        GET_TEMPLATES_METADATA: '/v3/template/metadata',
    },
    PERMISSION: {
        GET_PERMISSION: 'v3/permissions',
        ATTRIBUTES: 'v3/manager/attributes',
        LINK_ATTRIBUTES: 'v3/manager/attributes/link',
        UNLINK_ATTRIBUTES: 'v3/manager/attributes/unlink',
        ATTRIBUTE_VALUES: 'v3/manager/attributeValues',
        ATTRIBUTE_VALUES_BY_ACCOUNT: 'v3/manager/attributeValues/account',
        SYNC: 'v3/manager/attributes/metabase/sync',
    },
    CATALOGUE: {
        GET_CATALOGUE: 'v3/sheets/getCatalogueData',
        GET_PRODUCT_LIST: `v4/sheets/getCatalogueData/widget`,
        SUBMIT_CATALOGUE: `v4/sheets/catalogueData/submission`,
    },
    DATA_SOURCE: {
        MAIN: 'v4/data-source',
        LIST: 'v4/data-source/list',
        PREVIEW_DATA: 'v4/data-source/previewdata',
        LIVE_DATA: 'v4/data-source/live-data',
        DOWNLOAD_LIVE_DATA: 'v4/data-source/live-data',
        BULK_DELETE: 'v4/data-source/bulk-delete',
    },
    PROXIES: {
        GET_PROXY_LIST: `v4/proxy/List`,
        MAIN: `v4/proxy`,
        PUBLIC_PROXIES: 'v4/publicproxies',
        TOKEN: 'v4/public/proxy/refreshToken',
        PUBLIC_MAIN: 'v4/public',
        VERIFY_TOKEN: `v4/public/proxy/verifyToken`,
        PUBLISH_AUTOMATION: `v4/proxy/publish`,
        CLONE_PROXY: `v4/proxy/clone`,
        GET_PAGE_TEMPLATES: `v3/layout/getLayouts`,
    },
    PAGE: {
        MAIN: `v4/page`,
        PAGE_CLONE: '/v4/page/clone',
        TRIGGER_ACTIONS: `v4/page/actions/trigger`,
        USER_TEAM_DATA: `v4/page/widget/getUserAndTeamData`,
    },
    NOTIFICATIONS: {
        GET_NOTIFICATION: `v4/notifications`,
        READ_NOTIFICATION: `/v4/notifications/read`,
        ON_READ_ALL: `v4/notifications/read/all`,
    },
    ROLE_BUILDER: {
        CREATE_ROLE: `v4/attributes`,
        ALL_ROLE: `v4/attributes/list`,
    },
    LOCATION_TRACKING: {
        SESSION: `v4/page/maps/sessions`,
        LOCATION_DATA: `v4/page/maps/locationData`,
        LIVE_STATUS: `v4/location-tracking/live-status`,
        TIMELINE: `v4/location-tracking/timeline`,
        SETTINGS: `v4/location-tracking/settings`,
    },
    AI_BUILDER: {
        RUN_PROMPT: `v4/openai/visualization`,
    },
    ZAPIER: {
        GENERATE_API_KEY: 'v3/zapier/generateApiKey',
    },
    API_KEYS: {
        GET_KEY: 'v3/organization/getOrganizationKeyValue',
        UPDATE_KEY: 'v3/organization/addOrganizationKeyValue',
    },
};


export default API_END_POINTS;